# Generated by Django 4.2.4 on 2023-08-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('creation_date',)},
        ),
    ]
